os: linux
dist: xenial
sudo: false
language: python
python:
  - "3.7.4"
  - "3.8"
  - "nightly"

before_install:
  - sudo apt-get install -qq libxml2-dev libxmlsec1-dev libxslt-dev
  - sudo apt-get install -qq python-dev python-lxml python-libxml2
  - sudo apt-get install -qq python-libxslt1 libxml2
  - sudo apt-get install -qq build-essential

install:
  - pip install -U pip
  - pip install tox-travis

script:
  - tox

